# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from transport_server.models.base_model_ import Model
from transport_server import util


class Buyout(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, booking_id: int=None, status: str=None):  # noqa: E501
        """Buyout - a model defined in Swagger

        :param booking_id: The booking_id of this Buyout.  # noqa: E501
        :type booking_id: int
        :param status: The status of this Buyout.  # noqa: E501
        :type status: str
        """
        self.types = {
            'booking_id': int,
            'status': str
        }

        self.attribute_map = {
            'booking_id': 'bookingId',
            'status': 'status'
        }

        self._booking_id = booking_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Buyout':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Buyout of this Buyout.  # noqa: E501
        :rtype: Buyout
        """
        return util.deserialize_model(dikt, cls)

    @property
    def booking_id(self) -> int:
        """Gets the booking_id of this Buyout.


        :return: The booking_id of this Buyout.
        :rtype: int
        """
        return self._booking_id

    @booking_id.setter
    def booking_id(self, booking_id: int):
        """Sets the booking_id of this Buyout.


        :param booking_id: The booking_id of this Buyout.
        :type booking_id: int
        """

        self._booking_id = booking_id

    @property
    def status(self) -> str:
        """Gets the status of this Buyout.


        :return: The status of this Buyout.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Buyout.


        :param status: The status of this Buyout.
        :type status: str
        """

        self._status = status
