# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from transport_server.models.base_model_ import Model
from transport_server import util


class Sit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, class_name: str=None, sit_number: int=None, state: str='available', price: float=None):  # noqa: E501
        """Sit - a model defined in Swagger

        :param class_name: The class_name of this Sit.  # noqa: E501
        :type class_name: str
        :param sit_number: The sit_number of this Sit.  # noqa: E501
        :type sit_number: int
        :param state: The state of this Sit.  # noqa: E501
        :type state: str
        :param price: The price of this Sit.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'class_name': str,
            'sit_number': int,
            'state': str,
            'price': float
        }

        self.attribute_map = {
            'class_name': 'className',
            'sit_number': 'sitNumber',
            'state': 'state',
            'price': 'price'
        }

        self._class_name = class_name
        self._sit_number = sit_number
        self._state = state
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Sit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Sit of this Sit.  # noqa: E501
        :rtype: Sit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def class_name(self) -> str:
        """Gets the class_name of this Sit.


        :return: The class_name of this Sit.
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name: str):
        """Sets the class_name of this Sit.


        :param class_name: The class_name of this Sit.
        :type class_name: str
        """
        allowed_values = ["coach", "comfort", "business", "first"]  # noqa: E501
        if class_name not in allowed_values:
            raise ValueError(
                "Invalid value for `class_name` ({0}), must be one of {1}"
                .format(class_name, allowed_values)
            )

        self._class_name = class_name

    @property
    def sit_number(self) -> int:
        """Gets the sit_number of this Sit.


        :return: The sit_number of this Sit.
        :rtype: int
        """
        return self._sit_number

    @sit_number.setter
    def sit_number(self, sit_number: int):
        """Sets the sit_number of this Sit.


        :param sit_number: The sit_number of this Sit.
        :type sit_number: int
        """
        if sit_number is None:
            raise ValueError("Invalid value for `sit_number`, must not be `None`")  # noqa: E501

        self._sit_number = sit_number

    @property
    def state(self) -> str:
        """Gets the state of this Sit.


        :return: The state of this Sit.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this Sit.


        :param state: The state of this Sit.
        :type state: str
        """
        allowed_values = ["available", "not available"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def price(self) -> float:
        """Gets the price of this Sit.


        :return: The price of this Sit.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Sit.


        :param price: The price of this Sit.
        :type price: float
        """
        if price is None or price <= 0.0:
            raise ValueError("Invalid value for `price`, must not be `None` and must be positive")  # noqa: E501

        self._price = price
